export const GET_TEST_DETAILS = 'GET_TEST_DETAILS';
export const GET_SELECTED_QUESTIONS = 'GET_SELECTED_QUESTIONS';
export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER';
export const SET_TEST_ANSWERS = 'SET_TEST_ANSWERS';
