export const GET_TEST_LIST = 'GET_TEST_LIST';

export const GET_TEST_DETAILS = 'GET_TEST_DETAILS';
export const GET_SELECTED_QUESTIONS = 'GET_SELECTED_QUESTIONS';
export const GET_QUESTION_ANSWERS = 'GET_QUESTION_ANSWERS';
